name: copy_clip
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  shared_preferences: ^2.5.3
  flutter_speed_dial: ^7.0.0
  provider: ^6.1.5
  http: ^1.4.0
  groq_sdk: ^1.0.2
  flutter_dotenv: ^5.0.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
