/// Shared tag helpers.
///
/// Tags are free-form, user-created strings, but we enforce a small set of
/// rules so the tag list stays clean:
///
///  * lowercased, trimmed
///  * only `[a-z0-9-_]` (spaces are collapsed to `-`)
///  * max [kMaxTagLength] chars per tag
///  * max [kMaxTagsPerClip] tags per clip
///  * a reserved set of names is owned by the system (`url`, `email`, `code`,
///    `secret`) — users can't create or rename these.
library;

const int kMaxTagLength = 20;
const int kMaxTagsPerClip = 5;

/// System-owned tag names. Auto-generated by [autoTagsFor] and rendered
/// differently in the UI. Users can neither create nor delete these
/// explicitly — they follow the clip content.
const Set<String> kReservedTags = {'url', 'email', 'code', 'secret'};

final RegExp _tagChar = RegExp(r'[^a-z0-9\-_]');
final RegExp _whitespaceRun = RegExp(r'\s+');

/// Normalize a single user-typed tag. Returns `null` if the tag is empty
/// after cleanup or is a reserved system tag (users shouldn't be able to
/// add those manually).
String? normalizeUserTag(String raw) {
  var t = raw.trim().toLowerCase();
  if (t.isEmpty) return null;
  t = t.replaceAll(_whitespaceRun, '-');
  t = t.replaceAll(_tagChar, '');
  if (t.isEmpty) return null;
  if (t.length > kMaxTagLength) t = t.substring(0, kMaxTagLength);
  if (kReservedTags.contains(t)) return null;
  return t;
}

/// Normalize + dedupe a full list of tags (preserving order), and cap at
/// [kMaxTagsPerClip]. Reserved tags in the input are dropped — those are
/// added back via [autoTagsFor] at read time.
List<String> normalizeTagList(Iterable<String> raw) {
  final seen = <String>{};
  final out = <String>[];
  for (final r in raw) {
    final n = normalizeUserTag(r);
    if (n == null) continue;
    if (seen.add(n)) out.add(n);
    if (out.length >= kMaxTagsPerClip) break;
  }
  return out;
}

// --- auto-tag detection ---------------------------------------------------

final RegExp _urlRe = RegExp(
  r'^(https?:\/\/|www\.)[^\s]+$',
  caseSensitive: false,
);
final RegExp _emailRe = RegExp(
  r'^[^\s@]+@[^\s@]+\.[^\s@]+$',
  caseSensitive: false,
);
// A "looks like code" heuristic: multiple lines with braces / semicolons,
// or a fenced code block, or leading indentation on 2+ lines.
final RegExp _fencedRe = RegExp(r'```');
final RegExp _codeCharsRe = RegExp(r'[{};=<>]');

/// Heuristics for content that looks like a secret token / API key.
/// Deliberately conservative — false positives here would be worse than
/// missing a detection.
final RegExp _tokenPrefixRe = RegExp(
  r'^(sk_|pk_|ghp_|gho_|ghs_|xox[baprs]-|AKIA|ASIA)',
);
final RegExp _bearerRe = RegExp(r'^Bearer\s+[A-Za-z0-9\-_.]{16,}$');
final RegExp _longAlnumRe = RegExp(r'^[A-Za-z0-9\-_]{32,}$');

/// Compute the set of automatic tags for a given clip text. These are
/// re-derived on every read, so old data automatically picks them up.
Set<String> autoTagsFor(String text) {
  final t = text.trim();
  if (t.isEmpty) return const {};
  final tags = <String>{};

  // Single-line, whole-string checks.
  final singleLine = !t.contains('\n');
  if (singleLine) {
    if (_urlRe.hasMatch(t)) tags.add('url');
    if (_emailRe.hasMatch(t)) tags.add('email');
  }

  // Code heuristic.
  if (_fencedRe.hasMatch(t)) {
    tags.add('code');
  } else {
    final lines = t.split('\n');
    if (lines.length >= 2) {
      int codey = 0;
      for (final l in lines) {
        final indented = l.startsWith('  ') || l.startsWith('\t');
        final hasCodeChar = _codeCharsRe.hasMatch(l);
        if (indented || hasCodeChar) codey++;
      }
      if (codey >= 2) tags.add('code');
    }
  }

  // Secret heuristic — only apply to single-line, no-space content.
  if (singleLine && !t.contains(' ')) {
    if (_tokenPrefixRe.hasMatch(t) || _longAlnumRe.hasMatch(t)) {
      tags.add('secret');
    }
  } else if (_bearerRe.hasMatch(t)) {
    tags.add('secret');
  }

  return tags;
}
